steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud config set app/cloud_build_timeout 3600 \
        && gcloud app deploy --promote --project=pgde-dev

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '3600s'